### ISSUE TITLE
docker: cpp-clean-build fail

### ISSUE THREAD

**Issue by vanhauser-thc** [bmwcarit/joynr#10]
I am using ./joynr-docker build and after a successful run of 
docker run --rm --sig-proxy -e DEV_UID="1002" \
    -v /prg/tmp/joynr:/data/src \
    -v /prg/tmp/apache-maven-3.5.0:/home/joynr/.m2 \
    -v /prg/tmp/build:/data/build \
    joynr-cpp-gcc \
    /data/src/docker/joynr-cpp-base/scripts/build/cpp-generate.sh

I get a fail with 
docker run --rm --sig-proxy -e DEV_UID="1002" \
    -v /prg/tmp/joynr:/data/src \
    -v /prg/tmp/apache-maven-3.5.0:/home/joynr/.m2 \
    -v /prg/tmp/build:/data/build \
    joynr-cpp-gcc \
    /data/src/docker/joynr-cpp-base/scripts/build/cpp-clean-build.sh --jobs 4

[ 18%] Building CXX object libjoynr/CMakeFiles/Joynr.dir/in-process/generated/infrastructure/GlobalDomainAccessControllerInProcessConnector.cpp.o
[ 18%] Building CXX object libjoynr/CMakeFiles/Joynr.dir/in-process/generated/infrastructure/GlobalDomainRoleControllerInProcessConnector.cpp.o
{standard input}: Assembler messages:
{standard input}:240693: Warning: end of file not at end of a line; newline inserted
{standard input}:240938: Error: expected comma after name `_ZSt11_' in .size directive
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [libjoynr/CMakeFiles/Joynr.dir/in-process/generated/infrastructure/GlobalDomainAccessControlListEditorInProcessConnector.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
libjoynr/CMakeFiles/Joynr.dir/build.make:1478: recipe for target 'libjoynr/CMakeFiles/Joynr.dir/in-process/generated/infrastructure/GlobalDomainAccessControlListEditorInProcessConnector.cpp.o' failed
make[1]: *** [libjoynr/CMakeFiles/Joynr.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/Makefile2:244: recipe for target 'libjoynr/CMakeFiles/Joynr.dir/all' failed
Makefile:127: recipe for target 'all' failed

is this a known issue?

**Comment by manuel-schiller** [comment]
`c++: internal compiler error: Killed (program cc1plus)` sounds like the compiler is killed by the OS, possibly due to using to much resources. This can occur if you are running docker in a VM with limited resources (such as RAM).

You can try building with fewer parallel build jobs:

    /data/src/docker/joynr-cpp-base/scripts/build/cpp-clean-build.sh --jobs 2

**Comment by vanhauser-thc** [comment]
yes that was the issue, thanks!
I would have thought that 4GB of RAM would have been enough for four parallel compile jobs ...
