### ISSUE TITLE
Release Notes for JOYnr 0.25.X

### ISSUE THREAD

**Issue by gataka** [bmwcarit/joynr#11]
Hello JOYnr Developer,

please append the release notes for JOYnr 0.25.x, so the developer, who should integrate this version know whats changed and if there are some tasks to do.

Thank you,
Br
Philipp Beyerlein

**Comment by manuel-schiller** [comment]
The release notes are already up to date::

https://github.com/bmwcarit/joynr/blob/0.25.1/wiki/ReleaseNotes.md#joynr-0251
