### ISSUE TITLE
Joynr Android Runtime problem

### ISSUE THREAD

**Issue by dgambin72** [bmwcarit/joynr#12]
We are new in Joynr environment and we are trying to configure Android Runtime.

The build process seems to be fine and we are able to create through eclipse (neon) the android-location-provider and android-location-consumer apks.

We are not able to have the apks up&running 
The android-location-consumer crashes when we tap the "Create Joynr Proxy" button but we have an "joynr runtime not started" error when application starts.
Attached logcat report.

In the android-location-provider when we tap the "Start Joynr Runtime" button  we have actually a "joynr runtime started" message but application crashes when we press "Register Location Provider"
Attached logcat report.

We wonder if we have all required dependencies installed on android device and if the java build process it's enough to have a complete joynr android runtime environment or if we need some specific action for android application.

NOTE: looking at [Building Joynr Java](https://github.com/bmwcarit/joynr/blob/e40d8d802f18b8a6c398abfb127579f16cb62b8c/wiki/java_building_joynr.md) it seems to us that running 
   cd <JOYNR>/docker
   <JOYNR>/docker$ ./joynr-docker build
includes the android image build which is listed among the available images

Are we missing anything?

Thanks in advance
[android-location-provider.error.txt](https://github.com/bmwcarit/joynr/files/989509/android-location-provider.error.txt)
[android-location-consumer.error.txt](https://github.com/bmwcarit/joynr/files/989511/android-location-consumer.error.txt)

Regards
Alex, Domenico

**Comment by manuel-schiller** [comment]
closing since no reaction from OP
