### ISSUE TITLE
Enforcer rules Fail

### ISSUE THREAD

**Issue by reichl10** [bmwcarit/joynr#14]
Hi,

Today I was trying to build JoyNR with Maven 3.5, but it failed with the message that I'm using the wrong version. As 3.5 is the version recommended by Apache, could you please take a look at it?
Message: "Wrong maven version. You must use use Maven 3.1.x to 3.3.x to build joynr"
With kind regards,
Sebastian Reichl

**Comment by manuel-schiller** [comment]
this is fixed on develop branch now, will be part of 0.27.0
