### ISSUE TITLE
SSL Properties

### ISSUE THREAD

**Issue by lbenthins-adesso** [bmwcarit/joynr#21]
Hello, 

we must use SSL for the communication between Joynr and an MQTT broker instace. To enable SSL, we added the following properties to our Joynr properties (@JoynrProperties):

PROPERTY_KEY_MQTT_KEYSTORE_PATH
PROPERTY_KEY_MQTT_TRUSTSTORE_PATH
PROPERTY_KEY_MQTT_KEYSTORE_PWD
PROPERTY_KEY_MQTT_TRUSTSTORE_PWD

The properties are set correctly (I can see that when I set a breakpoint in DefaultJoynrRuntimeFactory). However, when the SSL properties are injected in MqttPahoClientFactory, the default system properties (e.g., PROPERTY_KEY_MQTT_TRUSTSTORE_PWD=changeit) are used instead. This only happens for the SSL properties.

Have somebody any idea where the problem is?

Thanks!

**Comment by manuel-schiller** [comment]
we found out that JEE overwrites those properties, hence the properties were moved from `javax.net.*` to `joynr.messaging.mqtt.*`

see

https://github.com/bmwcarit/joynr/commit/9402d49835797812f59da4ce50d250965f003e20

this is resolved in joynr 1.2.0
