### ISSUE TITLE
Invalid links in wiki/JavaScriptTutorial.md

### ISSUE THREAD

**Issue by rendner** [bmwcarit/joynr#23]
The links in [JavaScriptTutorial.md#starting-the-backend](https://github.com/bmwcarit/joynr/blob/master/wiki/JavaScriptTutorial.md#starting-the-backend) (`JEE Developer Guide` and `Radio App Tutorial`) contain the path `wiki` twice.

**Comment by manuel-schiller** [comment]
thanks for reporting, this is now fixed
