### ISSUE TITLE
Dose the cluster controller support proxy configuration

### ISSUE THREAD

**Issue by feifrank** [bmwcarit/joynr#25]
Hi,
I wonder that can I configure the Mqtt client which inside the cluster controller to use the proxy instead of directing connecting to the broker?
I can't find some related document about that.
Thanks.
BRs//Teng Fei

**Comment by manuel-schiller** [comment]
which kind of proxy are you referring to?

**Comment by feifrank** [comment]
Could be either socks5 or http proxy 

发自我的 iPhone

**Comment by feifrank** [comment]
I am sorry , better use http proxy

**Comment by manuel-schiller** [comment]
There is no way to use MQTT over a HTTP proxy in the MQTT libraries that are used in joynr.

**Comment by mitesh-mutha** [comment]
I was wondering if it is possible to do this now - use MQTT/Joynr over a HTTP or SOCKS5 proxy?
