### ISSUE TITLE
SMRF Prioritisation

### ISSUE THREAD

**Issue by JaehoonLeee** [bmwcarit/joynr#26]
Hi, All.

Regarding SMRF Prioritisation,
I wonder if Joynr Cluster Controller supports SMRF prioritisation.
I have analyzed code and SMRF packet, and checked priority header in SMRF message.
But,  I couldn't find prioritisation logic in code and operation.

Could you comment regarding it?

Thank you.

**Comment by manuel-schiller** [comment]
which priority header in SMRF are you refering to?
there is no such header in SMRF, see https://github.com/bmwcarit/smrf/blob/master/schema/smrf.fbs

**Comment by JaehoonLeee** [comment]
Thank you reply.
I tested using Radio App.
And,

In RadioApp Provider application,
I used setPriority() API.
types::ProviderQos providerQos;
    providerQos.setPriority(millisSinceEpoch.count());

In SMRF Packet,
I finded priority header.
{"sender":"e6c8627a-b770-40f4-8745-d26cdafb38b7","recipient":"capabilitiesdirectory_participantid","expiryDate":1526889164675,"headers":{"t":"rq","re":"{\"_typeName\":\"joynr.system.RoutingTypes.MqttAddress\",\"brokerUri\":\"tcp://localhost:1883\",\"topic\":\"ee953858-1d5b-4e18-9a2d-3ba2dd3106e3\"}","id":"444e61a4-25da-4e36-8051-1458ec597c50","c-z4":"9a87f0b9-f5d8-43c1-94d5-a9bd694d8088"},"receivedFromGlobal":false,"creator":"","payload":"{\"_typeName\":\"joynr.Request\",\"methodName\":\"add\",\"paramDatatypes\":[\"joynr.types.GlobalDiscoveryEntry\"],\"params\":[{\"_typeName\":\"joynr.types.GlobalDiscoveryEntry\",\"providerVersion\":{\"_typeName\":\"joynr.types.Version\",\"majorVersion\":0,\"minorVersion\":0},\"domain\":\"io.joynr\",\"interfaceName\":\"vehicle/Radio\",\"participantId\":\"e62a26e6-d962-44c7-95cf-df71d350dea7\",\"qos\":{\"_typeName\":\"joynr.types.ProviderQos\",\"customParameters\":[],\"**priority\":1526889104660**,\"scope\":\"GLOBAL\",\"supportsOnChangeSubscriptions\":true},\"lastSeenDateMs\":1526889104660,\"expiryDateMs\":1530517904660,\"publicKeyId\":\"\",\"address\":\"{\\\"_typeName\\\":\\\"joynr.system.RoutingTypes.MqttAddress\\\",\\\"brokerUri\\\":\\\"tcp://localhost:1883\\\",\\\"topic\\\":\\\"ee953858-1d5b-4e18-9a2d-3ba2dd3106e3\\\"}\"}],\"requestReplyId\":\"9a87f0b9-f5d8-43c1-94d5-a9bd694d8088\"}"}

**Comment by manuel-schiller** [comment]
This is the priority of the provider, please see the documentation about it here:

https://github.com/bmwcarit/joynr/blob/master/wiki/cplusplus.md#the-discovery-quality-of-

> The priority used by the arbitration strategy HighestPriority is set by the provider through the call providerQos.setPriority().
