### ISSUE TITLE
wrong path to domain-access-controller-jee war file

### ISSUE THREAD

**Issue by rendner** [bmwcarit/joynr#29]
https://github.com/bmwcarit/joynr/blob/d65b7d8ad2a3bc2f83e3df826bdf166d1237a0d2/docker/joynr-javascript/scripts/build/javascript-clean-build#L44

The `domain-access-controller-jee*.war`  is located under `/data/src/java/backend-services/domain-access-controller-jee/target` instead of `/data/src/java/backend-services/discovery-directory-jee/target` as stated in the code.

**Comment by manuel-schiller** [comment]
Thanks, will be fixed with next release

**Comment by rendner** [comment]
Thanks, is now fixed.
