### ISSUE TITLE
Java: MqttPahoClientTest test fails because keystore and  truststore are not always present

### ISSUE THREAD

**Issue by rendner** [bmwcarit/joynr#30]
### Problem
Running the tests in `MqttPahoClientTest` results in test errors if `clientkeystore` and `catruststore` are not present. The required files are created only through `docker/joynr-android/scripts/build/java-android-clean-build`. So running `docker/joynr-java/scripts/build/java-clean-build` will result in test errors, if these files where not created before.

The following error is reported:
```
Running io.joynr.messaging.mqtt.paho.client.MqttPahoClientTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.664 sec <<< FAILURE! - in io.joynr.messaging.mqtt.paho.client.MqttPahoClientTest
mqttClientTestWithDisabledMessageSizeCheckWithTlsAndDefaultJksStore(io.joynr.messaging.mqtt.paho.client.MqttPahoClientTest)  Time elapsed: 0.243 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.joynr.messaging.mqtt.paho.client.MqttPahoClientTest.getResourcePath(MqttPahoClientTest.java:158)
	at io.joynr.messaging.mqtt.paho.client.MqttPahoClientTest.mqttClientTestWithDisabledMessageSizeCheckWithTlsAndDefaultJksStore(MqttPahoClientTest.java:310)


Results :

Tests in error: 
  MqttPahoClientTest.mqttClientTestWithDisabledMessageSizeCheckWithTlsAndDefaultJksStore:310->getResourcePath:158 NullPointer
```

All users which follow this example [Building joynr Java and common components](https://github.com/bmwcarit/joynr/blob/master/wiki/java_building_joynr.md) will run into this problem. These errors don't prevent a successful build (`-Dmaven.test.failure.ignore=true` in `docker/joynr-java/scripts/build/java-clean-build`).

The required files have been added by commit [[Java] support MQTT TLS connection](https://github.com/bmwcarit/joynr/commit/5d995d4c988e71e5cfa45ba994adc1fa49bb169d) (Nov 29, 2017). 

### Steps to reproduce
-  Delete the following files, if present, from `java/messaging/mqtt/joynr-mqtt-client/src/test/resource`:
     - catruststore.jks
     - catruststore.p12
     - clientkeystore.jks
     - clientkeystore.p12
- Run the tests (replace FULL_PATH_TO_JOYNR_SOURCES and FULL_PATH_TO_MAVEN_DIRECTORY with the right values):
```
docker run -it --rm --sig-proxy -e DEV_UID="$(id -u)"  \
    -v <FULL_PATH_TO_JOYNR_SOURCES>:/data/src \
    -v <FULL_PATH_TO_MAVEN_DIRECTORY>:/home/joynr/.m2 \
    joynr-java \
    "mvn clean test -f /data/src/java/messaging/mqtt/joynr-mqtt-client/pom.xml -P no-license-and-notice,no-java-formatter,no-checkstyle -DskipTests=false -Dtest=MqttPahoClientTest"
```
- Or use the long way  (replace FULL_PATH_TO_JOYNR_SOURCES and FULL_PATH_TO_MAVEN_DIRECTORY with the right values):
```
docker run --rm --sig-proxy -e DEV_UID="$(id -u)"  \
    -v <FULL_PATH_TO_JOYNR_SOURCES>:/data/src \
    -v <FULL_PATH_TO_MAVEN_DIRECTORY>:/home/joynr/.m2 \
    joynr-java \
    /data/src/docker/joynr-java/scripts/build/java-clean-build
```

**Comment by ostkamp** [comment]
MqttPahoClient has  been discontinued in favor of HivemqMqttClient.
Today the container to be used is joynr-base as described on https://github.com/bmwcarit/joynr/blob/master/wiki/java_building_joynr.md.
For full tests use https://github.com/bmwcarit/joynr/blob/master/docker/joynr-base/scripts/ci/java-android-clean-build which also creates certs and invokes mosquitto and the required backend service.

This issue can be closed.
