### ISSUE TITLE
Build joynr C++ on Windows 10

### ISSUE THREAD

**Issue by andreisanta09** [bmwcarit/joynr#33]
Hi,

I want to build a JS Joynr application and it seems I need to build the C+ cluster controller first in order to run such an application (e.g. your radio app example).
Since I'm working on a Win 10 machine I am having troubles building the Joynr docker images as some scripts fail during `joynr-docker build`. 
e.g. : `/bin/sh: /data/scripts/gen-certificates.sh: /bin/bash^M: bad interpreter: No such file or directory`

This seems to happen because of the line break differences between Unix and Windows. 
Is this a known issue / expected behaviour ? 

PS : I can change the scripts manually to be saved in Unix format but I don't know which of them - might take a while to change them all based on the errors I get and also I would have to do this every time I make a new pull / rebuild.
Until now I was building the framework using Maven but that does not compile the cluster controller.

Thanks,
Andrei

**Comment by andreisanta09** [comment]
Hi,

Yes, I am using Docker (Docker CE) under Win 10 with Linux containers.
My problem is that since I am using Windows, whenever I checkout your code the line endings of the files are set to CRLF and then when a sh file runs into the container (Linux) the error above occurs.

I guess a simple fix would be to update your _.gitattribute_ file to always checkout sh files with LF (I used this in one of my projects): 
`*.sh text eol=lf`

Currently your _.gitattribute_ file has all file types set as `text` which will always convert them to native line endings.

I would assume that the error reported on issue #5 has the same root problem : boot2user.sh line ending is CRLF, running it in the container crashes (no idea how the build step worked).

Thanks,
Andrei

**Comment by manuel-schiller** [comment]
Thanks for your suggestion.
We'll check this and if applicable use it for our next release.

**Comment by manuel-schiller** [comment]
fixed in joynr 1.6.0
