### ISSUE TITLE
[Java] scripts with invalid shebang

### ISSUE THREAD

**Issue by rendner** [bmwcarit/joynr#37]
The following shell scripts have an invalid shebang `#/bin/bash`:

https://github.com/bmwcarit/joynr/blob/d89905cc1ebe004701cdb6dfed64bc05f4e535d1/docker/joynr-javascript/scripts/build/run-javascript-formatter#L1
https://github.com/bmwcarit/joynr/blob/85c997b12f5981d9ec6db90b8980e07a05a2af58/docker/joynr-java/scripts/build/run-java-formatter#L1
https://github.com/bmwcarit/joynr/blob/d65b7d8ad2a3bc2f83e3df826bdf166d1237a0d2/docker/joynr-android/scripts/build/run-java-android-formatter#L1
https://github.com/bmwcarit/joynr/blob/d89905cc1ebe004701cdb6dfed64bc05f4e535d1/docker/joynr-java/scripts/build/java-clean-build#L1
https://github.com/bmwcarit/joynr/blob/d89905cc1ebe004701cdb6dfed64bc05f4e535d1/docker/joynr-java/scripts/build/run-java-checks#L1
https://github.com/bmwcarit/joynr/blob/d65b7d8ad2a3bc2f83e3df826bdf166d1237a0d2/docker/joynr-android/scripts/build/run-java-android-checks#L1
https://github.com/bmwcarit/joynr/blob/d65b7d8ad2a3bc2f83e3df826bdf166d1237a0d2/docker/joynr-android/scripts/build/java-android-clean-build#L1

**Comment by donsciarra** [comment]
Thanks for reporting the issue, we will try to make this available in the next joynr release.

**Comment by donsciarra** [comment]
Fixed in joynr 1.7.0
