### ISSUE TITLE
Generator build failed

### ISSUE THREAD

**Issue by JinyoungKim0219** [bmwcarit/joynr#41]
Hi,
I'd like to ask regarding building generator.

I used to build JoynR in a server A, with aids of scripts 'cpp-generate.sh' and 'cpp-clean-build.sh'.
And I have opportunity to setup environment in another server, B.
When I run 'cpp-generate.sh' in docker, I get following error in building generator-framework and generation fails:

[INFO] ------------------------------------------------------------------------
[INFO] Building io.joynr.tools.generator:generator-framework 1.6.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ generator-framework ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:display-info (display-platform-info) @ generator-framework ---
[INFO] Maven Version: 3.3.9
[INFO] JDK Version: 1.8.0_141 normalized as: 1.8.0-141
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 4.4.0-140-generic
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-and-java-version) @ generator-framework ---
[INFO]
[INFO] --- maven-antrun-plugin:1.7:run (default) @ generator-framework ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:add-source (add-source) @ generator-framework ---
[INFO] Source directory: /data/src/tools/generator/framework/src/main/xtend-gen added.
[INFO]
[INFO] --- xtend-maven-plugin:2.11.0:compile (default) @ generator-framework ---
[WARNING] Compilation of stubs had errors.
[ERROR]
ERROR:  JoynrGeneratorExtensions.xtend - /data/src/tools/generator/framework/src/main/xtend/io/joynr/generator/templates/util/JoynrGeneratorExtensions.xtend
23: io.joynr.generator.templates.BroadcastTemplate cannot be resolved to a type.
[ERROR]
ERROR:  JoynrGeneratorExtensions.xtend - /data/src/tools/generator/framework/src/main/xtend/io/joynr/generator/templates/util/JoynrGeneratorExtensions.xtend
28: io.joynr.generator.templates.TypeDefTemplate cannot be resolved to a type.
[ERROR]
ERROR:  JoynrGeneratorExtensions.xtend - /data/src/tools/generator/framework/src/main/xtend/io/joynr/generator/templates/util/JoynrGeneratorExtensions.xtend
205: BroadcastTemplate cannot be resolved to a type.
[ERROR]
ERROR:  JoynrGeneratorExtensions.xtend - /data/src/tools/generator/framework/src/main/xtend/io/joynr/generator/templates/util/JoynrGeneratorExtensions.xtend
259: TypeDefTemplate cannot be resolved to a type.
[INFO] ------------------------------------------------------------------------

When not using docker, i.e., just run 'mvn clean install -P no-license-and-notice,no-java-formatter,no-checkstyle -DskipTests' at JoynR top dir, it shows the same error.

I try to find out why, then I find some interesting.
I tried to move '/home/user/.m2' from server A and run 'mvn' command, it also fails to generate. When I recover '/home/user/.m2', it works again.
And I copy '/home/user/.m2' from server A to server B, and it works in server B.
So, I'm generating code in server B as copying .m2 from server A as workaround, but it is not clear solution.

I don't know anything about maven or java, but in my opinion, it seems that settings like pom.xml is missing something comparing with past. Could you have a look at this problem, please?

**Comment by JinyoungKim0219** [comment]
Hello @lebenlechzer ,
Do you have any other errors

**Comment by JinyoungKim0219** [comment]
Hello @lebenlechzer ,
Do you have any other errors with code generation when switching xtend/xtext version?

**Comment by agegov** [comment]
Hi,

the problem was introduced with the release of some new Eclipse artifacts end of Dec 2018, e.g.: https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.core.runtime. As our direct dependencies declare version ranges for their dependencies, these new artifacts are now taken for the joynr build.  

We will provide a fix in the next joynr release (approx. end of January 2019). If you need a solution faster, please update in the main pom.xml the xtend.version and xtext.version to 2.16.0. Furthermore, update in the same file the section for the xtend-maven-plugin to:

`
...
<plugin>
	<groupId>org.eclipse.xtend</groupId>
	<artifactId>xtend-maven-plugin</artifactId>
	<version>${xtend.version}</version>
	<dependencies>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>21.0</version>
		</dependency>
	</dependencies>
</plugin>
...
`

**Comment by JinyoungKim0219** [comment]
Hello @agegov ,
Thank you for reply.
I'll check it after I change xml files.

**Comment by JinyoungKim0219** [comment]
Hello @agegov ,
I think those changes are updated in commit da1c7f4f3cf3c503cca9baa4809ca195ded9da61.
And I successfully generate code with master branch.
I'd like to close this issue. Thank you.
