### ISSUE TITLE
[Feature Request] Enable Multicast QOS configuration

### ISSUE THREAD

**Issue by kwakiutlCS** [bmwcarit/joynr#43]
To allow more configurable multicast is it possible to enable QOS configuration?

In PublicationManagerImpl#multicastOccurred(String providerParticipantId,
                                  String multicastName,
                                  String[] partitions,
                                  Object... values),
MessagingQos seems to be hardcoded to default qos (1) and default ttl.

Is it possible to configure some other way?
Thank you

**Comment by donsciarra** [comment]
Yes, currently the default MessagingQos maps to "io.joynr.messaging.MessagingQosEffort.NORMAL" which in turn maps at MQTT Level to the QoS=1.
Feel free to make a proposal so that we can discuss this further.
