### ISSUE TITLE
Building joynr Java and common components does not work on Windows

### ISSUE THREAD

**Issue by fsollinger** [bmwcarit/joynr#5]
I am using the docker toolbox for Windows 10 (64 Bit). Either the instructions on the page "Building joynr Java and common components" are incorrect / incomplete or there is an error in the scripts. Anyway the last step does not work.

Building the docker image with ./joynr-docker build does work fine. But when I enter:
`docker run --rm --sig-proxy -e DEV_UID="$(id -u)" -v /c/Projekte/joynr:/data/src -v /c/Users/fso/.m2:/home/joynr/.m2
joynr-java /data/src/docker/joynr-java/scripts/build/java-clean-build`
(where C:\Projekte\joynr is my joynr directory and C:\Users\fso\.m2 is my local maven repository), the result is:
`C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Container command '/data/scripts/boot2user.sh' not found or does not exist..`

Any ideas? Did I miss anything?

**Comment by david-katz** [comment]
Is there a permissions problem? This file is copied into the docker image, so should definitely be there. Could you try starting up a shell on the container and have a look if the file exists and what its access permissions are?

Thanks
David

**Comment by fsollinger** [comment]
Thanks for the reply.

Since I cannot start the container I can't check whether the file is actually there. To me it looks like the /data/scripts folder does not exist. However there were no errors during the execution of "joynr-docker build".

The file in the source folder (docker/joynr-base/scripts) does exist, is owned by me and executable by everybody.

If you can assure that it's not a bug in the build script then it's probably some configuration problem and you can close this issue.

Regards,
Florian
