### ISSUE TITLE
build joynr-java failed

### ISSUE THREAD

**Issue by g-traveller** [bmwcarit/joynr#55]
Hi, I try to build joynr java against guide: "https://github.com/bmwcarit/joynr/blob/master/wiki/java_building_joynr.md"
but error got:

INFO] clustercontroller-inprocess-runtime ................ SUCCESS [  2.149 s]
[INFO] io.joynr.java.messaging:mqtt ....................... SUCCESS [  0.842 s]
[INFO] io.joynr.java.messaging.mqtt:joynr-mqtt-client ..... FAILURE [ 46.420 s]
[INFO] io.joynr.java:jeeintegration ....................... SKIPPED
[INFO] io.joynr.java:backend-services ..................... SKIPPED

and the exception message is "io.joynr.messaging.mqtt.paho.client.MqttPahoClientTest.mqttClientTLSCreationFailsIfKeystorePasswordIsWrongOrMissing"

My build env: MacOS, docker engine 18.09

**Comment by ostkamp** [comment]
The guide now mentions the "skipTests" parameter that avoids running into the above situation.

$ docker run --rm --sig-proxy -e DEV_UID="$(id -u)"  \
    -v <FULL_PATH_TO_JOYNR_SOURCES>:/data/src \
    -v <FULL_PATH_TO_MAVEN_DIRECTORY>:/home/joynr/.m2 \
    joynr-base \
    /data/src/docker/joynr-base/scripts/test/java-clean-build skipTests
