### ISSUE TITLE
Double provider register in ClusteControllerRuntime

### ISSUE THREAD

**Issue by xinhuagu** [bmwcarit/joynr#68]
https://github.com/bmwcarit/joynr/blob/624bfa5c63512cebe7e7b66a7d8ca9752372cb27/java/core/clustercontroller/src/main/java/io/joynr/runtime/ClusterControllerRuntime.java#L78-L88

the codes for register duplicated itself , it does not make any sense

**Comment by christianhoff** [comment]
Actually, it is not a duplicate as the two calls register two different providers, i.e. localCapabilitiesDirectory and routingProvider.

**Comment by xinhuagu** [comment]
> Actually, it is not a duplicate as the two calls register two different providers, i.e. localCapabilitiesDirectory and routingProvider.

Thank you for the explaination.
